### ISSUE TITLE
robot_position.yaml

### ISSUE THREAD

**Issue by zgulkhan** [TehseenHasan/robotic-arm-pick-and-place-OpenCv-Python#1]
AoA Tehseen
I tried to compile your code, but gives error below. As I'm not good in python just newbie if you please help me to compile and run your code... Thanks
Traceback (most recent call last):
  File "F:\vision_sys\robotic-arm-pick-and-place-OpenCv-Python-main\Robot-OpenCV - Camera Coordinates - My Code.py", line 25, in <module>
    with open(r'Camera Calibration Algorithms/2. camera_calibration_tool-master/robot_position.yaml') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Camera Calibration Algorithms/2. camera_calibration_tool-master/robot_position.yaml'

Please help.....

**Comment by TehseenHasan** [comment]
Solved the issue. Updated the codes.
